#version: "3.8"
#services:
#  mysql:
#    image: mysql:8
#    container_name: mysql_container
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: Qwert1trewq!
#      MYSQL_DATABASE: couponsdb3
#    ports:
#      - "3306:3306"
#    networks:
#      - my_network
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "--silent"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  app:
#    build: .
#    container_name: JAVA_Container
#    restart: always
#    depends_on:
#      mysql:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/couponsdb3?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Qwert1trewq!
#    ports:
#      - "8080:8080"
#    networks:
#      - my_network
#
#networks:
#  my_network:
#    driver: bridge
