#For regular and cloud running of the application:
spring.datasource.username=root
spring.datasource.password=Qwert1trewq!
openai.api.key=REMOVED_OPENAI_KEY
openai.assistant.id=asst_2FWFzW8w2dyTBcmFKWtqiOP4

#For allow mailgun sent me a mail every time client enter to my app. this key is the private key to allow it
mailgun.api-key=REMOVED_MAILGUN_KEY
mailgun.domain=namir-coupons.shop

